version: '3'
services:
  app:
    image: strug-hub/gwas-svatalog
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sickkids.gwas-svatalog
    env_file: .env
    volumes:
      - ./data:/app/data
    ports:
      - '${DOCKER_HOST_PORT}:${PORT}'
